# Generated by Django 5.2.5 on 2025-08-18 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('min_num', models.PositiveIntegerField(default=0)),
                ('max_num', models.PositiveIntegerField(default=0)),
                ('max_player', models.PositiveIntegerField(default=0)),
                ('hide_room', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_code', models.CharField(blank=True, max_length=127, unique=True)),
                ('step_time', models.PositiveIntegerField(default=30)),
                ('order', models.JSONField(default=list)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='room_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
