# Generated by Django 5.2.5 on 2025-08-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to=settings.AUTH_USER_MODEL, verbose_name='current player'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hide_room',
            field=models.BooleanField(default=False, verbose_name='hide room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_num',
            field=models.PositiveIntegerField(default=100, verbose_name='maximum number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_player',
            field=models.PositiveIntegerField(default=20, verbose_name='maximum player number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='min_num',
            field=models.PositiveIntegerField(default=1, verbose_name='minimum number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=127, verbose_name='room name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='order',
            field=models.JSONField(default=list, verbose_name='player order'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='room_players', to=settings.AUTH_USER_MODEL, verbose_name='players'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=127, null=True, unique=True, verbose_name='room code'),
        ),
        migrations.AlterField(
            model_name='room',
            name='step_time',
            field=models.PositiveIntegerField(default=30, verbose_name='step time limit'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
