# Generated by Django 5.2.5 on 2025-08-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_room_options_alter_room_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('joining', '加入中'), ('ordering', '排序中'), ('preparing', '准备中'), ('playing', '进行中'), ('end', '结束'), ('ERROR', '错误')], default='not_playing', max_length=20, verbose_name='room status'),
        ),
    ]
