# Generated by Django 5.2.5 on 2025-08-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='New room', max_length=127, verbose_name='room name'),
        ),
    ]
