# Generated by Django 5.2.5 on 2025-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_room_order_alter_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('joining', 'Joining'), ('ordering', 'Ordering'), ('preparing', 'Preparing'), ('playing', 'Playing'), ('end', 'End'), ('ERROR', 'ERROR')], default='not_playing', max_length=20, verbose_name='room status'),
        ),
    ]
