# Generated by Django 5.2.5 on 2025-08-20 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='answer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='room',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to=settings.AUTH_USER_MODEL, verbose_name='loser'),
        ),
        migrations.AddField(
            model_name='room',
            name='ready_players',
            field=models.ManyToManyField(blank=True, related_name='room_ready_players', to=settings.AUTH_USER_MODEL, verbose_name='ready players'),
        ),
    ]
