# Generated by Django 5.2.5 on 2025-08-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_room_answer_room_loser_room_ready_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('joining', 'Joining'), ('ordering', 'Ordering'), ('preparing', 'Preparing'), ('playing', 'Playing'), ('end', 'End'), ('ERROR', 'ERROR')], default='joining', max_length=20, verbose_name='room status'),
        ),
    ]
